### ISSUE TITLE
[JOSS 6532] Expose API docs

### ISSUE THREAD

**Issue by dfm** [NIFTy-PPL/JAXbind#12]
While the public interface functions do seem to have good docstrings, and there are nice examples of usage, the API docs are not sufficiently accessible by JOSS standards.

Related to #8 

ref: https://github.com/openjournals/joss-reviews/issues/6532

**Comment by roth-jakob** [comment]
Yes, I agree, just having docstrings is a bit lazy. With #13 we export the documentation as a website. Here is the URL https://nifty-ppl.github.io/JAXbind/index.html

**Comment by dfm** [comment]
This looks good to me! I think that a bit more expository technical text setting the stage for what the different parts of the API do (related to discussion in #10) would be helpful, but I think this is sufficient for the JOSS review.

**Comment by Edenhofer** [comment]
Agreed, I'll amend the documentation in this direction. I will probably only be able to do so in a couple of days though (hopefully less than 2 weeks) due to time constraints.

**Comment by roth-jakob** [comment]
Thanks! Let's merge #13 first and work on #10 in a separate PR.
