### ISSUE TITLE
[JOSS 6532] Clarify what "any function" means

### ISSUE THREAD

**Issue by dfm** [NIFTy-PPL/JAXbind#18]
This is related to some of the other issues that I've raised, and I think the docs are getting better, but I think there should be a bit more clarity at the top of the README and on the first page of the docs to better motivate what this module does. I'd say that the key point here is that it allows you to expose any functions that can be called from **Python**, even if it's not written using JAX primitives itself. Right now I feel like the docs aren't quite specific enough about what the use case is here.

ref: https://github.com/openjournals/joss-reviews/issues/6532

**Comment by roth-jakob** [comment]
Thanks for the feedback! With PR #21 we try to make this clearer. Please let us know if you think further clarification on the use case of JAXbind is needed.

**Comment by dfm** [comment]
#21 looks good to me - thanks!

**Comment by dfm** [comment]
I wanted to comment here to note that the JOSS paper should also include some of this updated language. The paper text is still a bit vague on these points. I'm happy to open a separate issue if that would be useful.

**Comment by roth-jakob** [comment]
Thanks for your comment!

You might have read the old PDF version from the JOSS issues. I have now updated the PDF in JOSS. Sorry that I forgot about it earlier.

Additionally, with PR #22, we have updated the summary section of the paper. Please let me know if anything is still unclear.

**Comment by dfm** [comment]
Great - thanks!
