### ISSUE TITLE
[JOSS 6532] Expand and clarify contribution guidlines

### ISSUE THREAD

**Issue by dfm** [NIFTy-PPL/JAXbind#19]
One of the JOSS review requirements is that submissions have clear contribution guidelines, but I couldn't find them documented for JAXBind. This should probably include developer docs and info about issue/PR expectations, for example.

ref: https://github.com/openjournals/joss-reviews/issues/6532

**Comment by Edenhofer** [comment]
Thanks for your comment! Is #20 sufficient or shall the contributions guide be more detailed?

**Comment by dfm** [comment]
I'd say that that does satisfy the letter of the JOSS requirements, but perhaps doesn't present the most welcoming face to new developers. I leave it up to you to decide if this is sufficient for your purposes!

**Comment by Edenhofer** [comment]
Thanks! You're right. The section reads really grumpy. I probably woke up on the wrong side of the bed yesterday :grimacing: 

Hope it reads much friendlier now :)
