### ISSUE TITLE
[JOSS 6532] Improve related work

### ISSUE THREAD

**Issue by hawkinsp** [NIFTy-PPL/JAXbind#28]
Something that I think the related work section should at least discuss is how this work relates to the mechanisms for binding foreign functions into PyTorch and TensorFlow. It's probably worth at least a paragraph describing similarities and differences.

**Comment by danielskatz** [comment]
For JOSS review https://github.com/openjournals/joss-reviews/issues/6532

**Comment by roth-jakob** [comment]
Thanks for the feedback! I agree that this might be interesting to some readers. I will look into the TensorFlow and PyTorch functionality.

**Comment by roth-jakob** [comment]
With #30, we add a short paragraph about the PyTorch and TensorFlow interfaces for custom functions. Is this what you had in mind?
